### ISSUE TITLE
Human DE experiments in Atlas using cell lines with no disease studied

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data-providers-docs#14]
@iandunham @deniseOme 

On 02/03/2017 09:38, Open Targets Support wrote:
>
> oops...
>
>
> How did we associate ENSG00000100628 with EFO_0000365 based on this entry?
>
>
> http://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-3649/
>
> I did not know we had ArrayExpress data (unless it was in Expression Atlas)?!?!?
>
>
> Thanks,
> Denise
>
>
> From: George Locke 
> Sent: 01 March 2017 18:16
> To: Open Targets Support
> Subject: false positive report
>  
> Hi,
>
> I'm just writing to report a spurious gene-disease association apparently based on faulty text mining.  If there is another email address for reporting such findings, or if they're not useful to you, please let me know.
>
> https://www.targetvalidation.org/evidence/ENSG00000100628/EFO_0000365
> 	
> Target Validation platform
> www.targetvalidation.org
> The Target Validation platform brings together information on the relationships between potential drug, targets and diseases.
>
>
>
> Here, it is reported that ASB2 is associated with colorectal cancer based on differential RNA expression.  The study that is quoted to support this association examined lysteria infection - nothing to do with cancer at all!
>
> Hopefully you can use my report to improve your text mining :)
>
> Regards,
> George

**Comment by ckongEbi** [comment]
@deniseOme fyi

**Comment by deniseOme** [comment]
Is this repo public? If so, I'd have thought we may need to remove names and email addresses...

**Comment by emepyc** [comment]
Good point @deniseOme. Yes, this repo is public

**Comment by ckongEbi** [comment]
can we restrict access to listed users? @emepyc

**Comment by ckongEbi** [comment]
>
>
> On 09/03/2017 11:40, Laura Huerta Martinez wrote:
>>
>> Hi ChuangKee,
>>
>> Robert has been having a look at all cases in Expression Atlas which have cell line as a sample characteristic, but no disease as a factor and this is the list of experiments:
>>
>> http://www.ebi.ac.uk/~rpetry/ot/human_cell_line_with_no_disease_factor.txt
>>
>> Let me know if that helps,
> Thanks Laura, we'll have a look and get back on the action.
>
> Cheers,
> ChuangKee

**Comment by ckongEbi** [comment]
Awating Robert feedback on experiments that contains OT evidence.

**Comment by ckongEbi** [comment]
On 05/05/2017 23:46, Chuang Kee Ong wrote:
>
> Hi All,
>
>      There are 274 studies of cell lines with no disease as an experimental variable currently in the OT platform (attached), this will translate into ~260k evidence with "unknown" target activity. About 75% of the total expression atlas evidence has "unknown" target activity.
> Do we want to manually curate these to decide which studies has relevant phenotype?
>
> Cheers,
> ChuangKee

![screen shot 2017-05-05 at 23 07 53](https://cloud.githubusercontent.com/assets/6169985/25766950/92c933ae-31ed-11e7-9682-875231a0b4c3.png)
[atlas_studies.xlsx](https://github.com/opentargets/data-providers-docs/files/980479/atlas_studies.xlsx)

Cheers,
ChuangKee

**Comment by ckongEbi** [comment]
@iandunham do you feel we should removed studies (on cell line without disease factor) in the platform currently and/or down-weight them accordingly.

**Comment by iandunham** [comment]
We should definitely downweight them - do we do that already. Have we assembled a sample of these studies with their titles and factors? I's like to get a feel for whether they can really be thought of as relevant to disease.

**Comment by ckongEbi** [comment]
@iandunham , from the code I can see that the evidence scores calculation for expression takes into account log2fc & p-value but not the confidence level.

2. This is the list of studies which I curated manually, but they do not have the title and factors now
[atlas_studies.xlsx](https://github.com/opentargets/data-providers-docs/files/984139/atlas_studies.xlsx)

**Comment by apierleoni** [comment]
It is not used and was never intended to. if we want to link target to diseases only of it is a normal vs disease, I would suggest to drop the other evidence strings, and capture their meaning in a more appropiate place.

**Comment by iandunham** [comment]
Yes, That's what we are working through. I want to get a clear idea of the studies and factors, and then decide to drop these.

**Comment by ckongEbi** [comment]
@apierleoni 75% of our current atlas evidence strings will be removed, you can find definition of the confidence level here:
https://github.com/opentargets/data-providers-docs/wiki/Data-(Evidence-Strings)-Generation-Process

@iandunham , started adding information around the studies here, see if this helps and I can do the rest. 
https://docs.google.com/spreadsheets/d/1o0WURMDT3YW7YK6TA-aIIBo6OeNowqbvagkbx7PQub0/edit#gid=0

**Comment by ckongEbi** [comment]
atlas will exclude these 274 studies currently in platform (17.04) from subsequent run

[studies_to_remove.txt](https://github.com/opentargets/data-providers-docs/files/1010651/studies_to_remove.txt)

**Comment by ckongEbi** [comment]
@iandunham closing this as atlas has address the removal of studies on human cell line & disease not a in the study factor.
