### ISSUE TITLE
Nanophthalmia versus microphthalmia

### ISSUE THREAD

**Issue by deniseOme** [opentargets/data-providers-docs#19]
Nano is used as a synonym for micro but they could be different diseases according to:
https://en.wikipedia.org/wiki/Microphthalmia

They are separate in EFO and therefore the Platform but one is used as synonym of the other which messes up the evidence coming from text mining:

https://www.targetvalidation.org/evidence/ENSG00000006042/EFO_0005569?view=sec:literature

We need to confirm the relationship of these two diseases with EFO colleagues.

**Comment by ckongEbi** [comment]
@deniseOme @gkos-bio @iandunham  This is a EFO specific issue, can you move/re-create in below repo, usually Gautier will gather EFO related issues there and submit to Sira to address them. 

https://github.com/opentargets/platform_semantic/issues

The practise/agreement is we separate data-providers & efo/ontology related issues between us (me & Gautier) , hope this make sense. 

Thanks

**Comment by deniseOme** [comment]
Thanks @ckongEbi.

JIRA ticket created instead! @gkos-bio @iandunham 

https://www.ebi.ac.uk/panda/jira/browse/FGPTO-1391

**Comment by ckongEbi** [comment]
close as JIRA created for SPOT team
