### ISSUE TITLE
"unknown" activity in differential expression table (Evidence page) not informative

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/data-providers-docs#20]
The tables reporting differential expression comparisons on the Evidence page seem to mostly report "unknown" under the Activity column. 

This isn't very informative, the users expect "up/down" instead.

Examples:

https://www.targetvalidation.org/evidence/ENSG00000073756/EFO_0003767?view=sec:rna_expression
1 comparison is labeled as "increased", 14 are labelled as "unknown".

https://www.targetvalidation.org/evidence/ENSG00000103375/EFO_0003767?view=sec:rna_expression
3 comparisons are labelled as "decreased", 12 are labelled as "unknown".

Notice that if you click on the "unknown" link, the comparison on the heatmap in the Atlas page is presented either as blue (decreased) or red (increased). So what we show in our table is not consistent with what Atlas shows on their heatmaps. 

We need to decide:
1. Should the "unknown" comparisons be included as evidence that supports a target-disease association?
2. If they should be included, can the column be labeled in a more informative way?

This is a tentative proposal for 2:

condition 1		| condition 2      					| activity
disease tissue  	| healthy tissue 					| decreased 
disease tissue 	| treatment with X drug after N hours	| increased

**Comment by ckongEbi** [comment]
This list here contribute largely to the "unknown" evidence, we are curating it and they will be removed from atlas in 17.06

https://docs.google.com/spreadsheets/d/1o0WURMDT3YW7YK6TA-aIIBo6OeNowqbvagkbx7PQub0/edit#gid=0

**Comment by ckongEbi** [comment]
@nikiforosk list of studies above are removed from 17.06, we have seen a significant dropped in evidence with target_activity 'unknown'. 
`17.04 => 432,862, 17.06 => 171, 645`
