### ISSUE TITLE
missing genetic information for CHD

### ISSUE THREAD

**Issue by deniseOme** [opentargets/data-providers-docs#23]
Hi @ckongEbi @iandunham 

This recent paper highlights/summarises known mutations associated with CHD:
https://www.nature.com/nature/journal/v544/n7649/full/nature22034.html#affil-auth

including APOC3 p.Arg19Ter (which is the HGVS notation for rs76353203).

We don't have any genetic association for this pair of target/disease:
https://www.targetvalidation.org/evidence/ENSG00000110245/EFO_0001645

There may be missing mutations for other genes too in this disease.

It may be worth contacting Barbara and see if she can curate this otherwise it will be picked up by text mining only and therefore the score down weighted.

**Comment by deniseOme** [comment]
Also the link between this SNP (or gene) and the disease is in Ensembl already:

http://www.ensembl.org/Homo_sapiens/Variation/Phenotype?db=core;g=ENSG00000110245;r=11:116829706-116833072;v=rs76353203;vdb=variation;vf=16171684

As the variant is in ClinVar, so maybe this should be in EVA?

http://www.ensembl.org/Homo_sapiens/Gene/Variation_Gene/Table?g=ENSG00000110245;r=11:116829706-116833072

The mutation is a stop gain from an Arg.

**Comment by iandunham** [comment]
Yes, we should see whether this type of data will get into Clinvar or EVA. Also good to discuss with Maya as she will look at including other types of genetic data. Although part of the point of this paper is that the LoF homopzygotes actually don't have disease - the APOC KO mutation has a positive effect in these cases. Note that we do have associations via rs121918382 to the effect of this gene on plasma triglyceride levels.

**Comment by ckongEbi** [comment]
New in the 17.04 eva submission we do have evidence for association to Hyperalphalipoproteinemia 2
https://www.ncbi.nlm.nih.gov/clinvar/RCV000019493/

but NOT Coronary heart disease, as the clinical significance is not 'pathogenic' , clinvar might update this with the recent publication pointed out above. 
https://www.ncbi.nlm.nih.gov/clinvar/RCV000128448/

**Comment by deniseOme** [comment]
he odd thing is that Ensembl does have it as pathogenic, and that information comes from ClinVar (http://www.ensembl.org/info/genome/variation/data_description.html#clin_significance):

![screen shot 2017-04-19 at 15 49 47](https://cloud.githubusercontent.com/assets/6472381/25186436/161e3d18-2518-11e7-8227-425cde7cdbe5.png)

@iandunham, I have talked to Maya who will be creating a GitHub account so that she can be included on this type of conversation.

**Comment by ckongEbi** [comment]
ensembl import from clinvar so they should be consistent. What I can see is that the rs_id has both clinical significance, but it is the 'protective' one associated with Coronary heart disease, therefore dropped in our evidence

![screen shot 2017-04-19 at 15 59 43](https://cloud.githubusercontent.com/assets/6169985/25186756/0146c49a-2519-11e7-8651-b683a2d7daf1.png)

**Comment by iandunham** [comment]
Ahhh! Ask EVA how many protective variants they have - we can ask for these but we will need to look at how we represent them vs pathogenic.

**Comment by ckongEbi** [comment]
From the clinvar definition protective => For variants that decrease the risk of a disorder, including infections. Do we want to include those? 
I can take up with EVA on how many are there.

**Comment by iandunham** [comment]
Yes, because they are evidence of an association with disease. But we need to work out how we represent these e.g. something in the evidebcetable that distinguishes protective vs pathogenic variants. This is not the same as negative evidence - it still shows that there is an association with disease for this gene.

**Comment by ckongEbi** [comment]
we will need to score them differently, let me can the figures from EVA and take it from there..

**Comment by deniseOme** [comment]
It seems the **pathogenic** status of rs76353203 in the pair APOC3-HYPERALPHALIPOPROTEINEMIA showed in Ensembl has not been picked up by us:

http://targetvalidation.org/evidence/ENSG00000110245/Orphanet_181428?view=sec:genetic_associations

Shouldn't it as it's not a protective status?

**Comment by iandunham** [comment]
It doesn't seem to be in EVA if you search for rs76353203.  Comes direct into Ensembl from Clinvar apparently - worth checking our why

**Comment by ckongEbi** [comment]
@iandunham  It should be clinvar -> dbsnp -> ensembl, we can see it there in eva.  

![screen shot 2017-04-19 at 16 58 16](https://cloud.githubusercontent.com/assets/6169985/25189639/a51e5b8e-2521-11e7-965d-dd16f690237a.png)

**Comment by iandunham** [comment]
It's the clinical browser you have to look in ..and it is there. So check why we don't get that

**Comment by ckongEbi** [comment]
yes, it is in the clinical browser as well, we do have the evidence for HYPERALPHALIPOPROTEINEMIA  in the 17.04 submission.

**Comment by ckongEbi** [comment]
@iandunham @deniseOme 
closing this as it is superseded by the general task of including all "protective" variants from eva
https://github.com/opentargets/data-providers-docs/issues/24
